package com.fullparam.qualcommglcontextbleedcrash

import android.content.Context
import android.os.Build
import android.os.Bundle
import android.os.Process
import android.util.Log
import android.view.View
import android.widget.Button
import android.widget.ScrollView
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import java.io.BufferedReader
import java.io.InputStreamReader
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.concurrent.Executors

class MainActivity : AppCompatActivity() {

    companion object {
        private const val TAG = "ADRENO_REPRO"
    }

    private lateinit var tvDeviceInfo: TextView
    private lateinit var tvStatus: TextView
    private lateinit var tvLogOutput: TextView
    private lateinit var scrollViewLog: ScrollView

    private lateinit var btnRunBaseline: Button
    private lateinit var btnRunRobustSafe: Button
    private lateinit var btnTriggerGviCrash: Button
    private lateinit var btnRunPoisoning: Button
    private lateinit var btnClearCache: Button
    private lateinit var btnClearLog: Button

    private val executor = Executors.newSingleThreadExecutor()
    private val logcatExecutor = Executors.newSingleThreadExecutor()
    private var logcatProcess: java.lang.Process? = null
    @Volatile
    private var isLogcatMonitoringActive = true

    private val timeFormat = SimpleDateFormat("HH:mm:ss.SSS", Locale.US)
    @Volatile
    private var isProcessPoisonedByRobustContext = false

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        tvDeviceInfo = findViewById(R.id.tv_device_info)
        tvStatus = findViewById(R.id.tv_status)
        tvLogOutput = findViewById(R.id.tv_log_output)
        scrollViewLog = findViewById(R.id.scroll_view_log)

        btnRunBaseline = findViewById(R.id.btn_run_baseline)
        btnRunRobustSafe = findViewById(R.id.btn_run_robust_safe)
        btnTriggerGviCrash = findViewById(R.id.btn_trigger_gvi_crash)
        btnRunPoisoning = findViewById(R.id.btn_run_poisoning)
        btnClearCache = findViewById(R.id.btn_clear_cache)
        btnClearLog = findViewById(R.id.btn_clear_log)

        initDeviceInfo()
        startLogcatMonitor()

        btnRunBaseline.setOnClickListener {
            runOnGlThread("1. Standard Context (Dynamic Indexing)") {
                executeBaselineTest()
            }
        }

        btnRunRobustSafe.setOnClickListener {
            runOnGlThread("2. Robust Context (Safe Shader)") {
                executeRobustSafeTest()
            }
        }

        btnTriggerGviCrash.setOnClickListener {
            runOnGlThread("3. Direct Driver Bug (Robust + Dynamic Indexing)") {
                executeTriggerGviCrashTest()
            }
        }

        btnRunPoisoning.setOnClickListener {
            runOnGlThread("4. Cross-Context Poisoning Test") {
                executePoisoningTest()
            }
        }

        btnClearCache.setOnClickListener {
            runOnGlThread("Clear Shader Cache") {
                executeClearCache()
            }
        }

        btnClearLog.setOnClickListener {
            tvLogOutput.text = ""
            logMessage("Log cleared.")
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        isLogcatMonitoringActive = false
        try {
            logcatProcess?.destroy()
        } catch (_: Exception) {
        }
        logcatExecutor.shutdownNow()
        executor.shutdown()
    }

    /**
     * Continuously reads process-level Logcat entries for our PID.
     * Captures native driver errors from libEGL, Adreno, libc asserts, etc.,
     * and displays them directly in the mini console so no native errors are missed.
     */
    private fun startLogcatMonitor() {
        logcatExecutor.execute {
            try {
                val pid = Process.myPid().toString()
                val process = ProcessBuilder(
                    "logcat",
                    "-v", "time",
                    "--pid=$pid",
                    "*:V",
                ).start()
                logcatProcess = process

                val reader = BufferedReader(InputStreamReader(process.inputStream))
                var line: String? = reader.readLine()
                while (isLogcatMonitoringActive && line != null) {
                    val currentLine = line
                    // Filter: Avoid duplicating lines generated by our own logMessage(),
                    // but capture native libEGL, Adreno, libc, DEBUG, or general system errors.
                    if (!currentLine.contains("ADRENO_REPRO") && isRelevantSystemLog(currentLine)) {
                        runOnUiThread {
                            appendConsoleMessage("[SYS] $currentLine")
                        }
                    }
                    line = reader.readLine()
                }
            } catch (e: Exception) {
                Log.d(TAG, "Logcat monitor ended: ${e.message}")
            }
        }
    }

    private fun isRelevantSystemLog(line: String): Boolean {
        val lower = line.lowercase(Locale.US)
        return lower.contains("libegl") ||
                lower.contains("adreno") ||
                lower.contains("eglcreatecontext") ||
                lower.contains("assertion failed") ||
                lower.contains("gvi") ||
                lower.contains("oob") ||
                lower.contains("fatal") ||
                lower.contains("crash") ||
                lower.contains("sigsegv") ||
                lower.contains("sigabrt") ||
                lower.contains("debug   :") ||
                line.contains(" E ") ||
                line.contains(" F ")
    }

    private fun initDeviceInfo() {
        val socInfo = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            " | SoC: ${Build.SOC_MODEL}"
        } else {
            ""
        }
        val baseInfo = "Device: ${Build.MANUFACTURER} ${Build.MODEL} | Hardware: ${Build.HARDWARE}$socInfo | Android: ${Build.VERSION.RELEASE} (API ${Build.VERSION.SDK_INT})"
        tvDeviceInfo.text = baseInfo

        // Query initial GPU renderer via a temporary standard context on background thread
        executor.execute {
            val engine = EglEngine()
            try {
                engine.init()
                engine.createContext(enableRobustness = false)
                engine.makeCurrent()
                val renderer = android.opengl.GLES20.glGetString(android.opengl.GLES20.GL_RENDERER) ?: "UNKNOWN"
                val version = android.opengl.GLES20.glGetString(android.opengl.GLES20.GL_VERSION) ?: "UNKNOWN"
                val vendor = android.opengl.GLES20.glGetString(android.opengl.GLES20.GL_VENDOR) ?: "UNKNOWN"
                val fullInfo = "$baseInfo\nGPU: $renderer ($vendor) | Driver: $version"
                runOnUiThread {
                    tvDeviceInfo.text = fullInfo
                }
                logMessage("GPU Initialized: $renderer ($version) | Vendor: $vendor")
            } catch (e: Exception) {
                Log.w(TAG, "Could not query initial GPU info: ${e.message}")
            } finally {
                engine.destroy()
            }
        }
    }

    private fun setButtonsEnabled(enabled: Boolean) {
        btnRunBaseline.isEnabled = enabled
        btnRunRobustSafe.isEnabled = enabled
        btnTriggerGviCrash.isEnabled = enabled
        btnRunPoisoning.isEnabled = enabled
        btnClearCache.isEnabled = enabled
    }

    private fun setStatus(status: String) {
        runOnUiThread {
            tvStatus.text = getString(R.string.status_idle).replace("Idle", status)
        }
    }

    private fun logMessage(msg: String) {
        val timestamp = timeFormat.format(Date())
        val formatted = "[$timestamp] $msg"
        Log.i(TAG, formatted)
        runOnUiThread {
            appendConsoleMessage(formatted)
        }
    }

    private fun logError(title: String, t: Throwable) {
        val timestamp = timeFormat.format(Date())
        val stackTrace = Log.getStackTraceString(t)
        val formatted = buildString {
            appendLine("[$timestamp] [ERROR] $title: ${t.message}")
            appendLine("Stack Trace:")
            append(stackTrace.trimEnd())
        }
        Log.e(TAG, formatted, t)
        runOnUiThread {
            appendConsoleMessage(formatted)
        }
    }

    private fun appendConsoleMessage(formatted: String) {
        if (tvLogOutput.text.isEmpty()) {
            tvLogOutput.text = formatted
        } else {
            tvLogOutput.append("\n$formatted")
        }
        scrollViewLog.post {
            scrollViewLog.fullScroll(View.FOCUS_DOWN)
        }
    }

    private fun runOnGlThread(testName: String, task: () -> Unit) {
        setButtonsEnabled(enabled = false)
        setStatus("Running $testName...")
        logMessage("==================================================")
        logMessage(">>> STARTING: $testName")

        executor.execute {
            try {
                task()
            } catch (t: Throwable) {
                logError("FATAL ERROR during $testName", t)
            } finally {
                runOnUiThread {
                    setStatus("Idle")
                    setButtonsEnabled(enabled = true)
                }
                logMessage("<<< FINISHED: $testName")
                logMessage("==================================================")
            }
        }
    }

    /**
     * Button 1: Standard Context (Dynamic Indexing) [Expect: PASS]
     * Regular EGL context (no robust access attributes).
     * Links Dynamic Indexing Shader (which WOULD crash if compiled under robust context).
     * Proves: The shader itself is valid OpenGL ES and passes cleanly in isolation.
     */
    private fun executeBaselineTest() {
        logMessage("Step 1: Clearing shader disk cache...")
        ShaderCacheUtil.disableShaderDiskCache(this)

        val engine = EglEngine()
        try {
            logMessage("Step 2: Initializing offscreen headless EGL...")
            engine.init()
            logMessage("Step 3: Creating standard (non-robust) EGL context: attribs=[0x3098, 2, 0x3038]...")
            engine.createContext(enableRobustness = false)
            engine.makeCurrent()

            logMessage("Step 4: Compiling & linking Dynamic Indexing Shader (and variants) on standard context...")
            val results = ShaderTestSuite.runAllVariants(salt = "baseline_${System.nanoTime()}")

            var passedCount = 0
            for (res in results) {
                logMessage(res.formattedOutput())
                if (res.linkSuccess) passedCount++
            }

            logMessage("SUMMARY: $passedCount/${results.size} shaders linked successfully.")
            if (passedCount == results.size) {
                logMessage("RESULT: BASELINE PASSED (Expected: Dynamic Indexing Shader links cleanly without robust access).")
            } else {
                if (isProcessPoisonedByRobustContext) {
                    logMessage("RESULT: BASELINE FAILED (Expected if run after Robust Context tests).")
                    logMessage("  NOTE: A robust context was previously created in this process session, which permanently poisoned the driver.")
                    logMessage("  Force-stop and restart the application to run a clean, unpoisoned baseline.")
                } else {
                    logMessage("RESULT: BASELINE FAILED (Unexpected link failure on standard context).")
                }
            }
        } finally {
            engine.destroy()
        }
    }

    /**
     * Button 2: Robust Context (Safe Shader) [Expect: PASS]
     * Creates an EGL context with EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT = 0x30BF.
     * Compiles a SAFE shader (loop unrolled / static constant indexing).
     * Proves: Robust access works normally when shaders do not use dynamic uniform indexing.
     */
    private fun executeRobustSafeTest() {
        isProcessPoisonedByRobustContext = true
        logMessage("Step 1: Clearing shader disk cache...")
        ShaderCacheUtil.disableShaderDiskCache(this)

        val engine = EglEngine()
        try {
            logMessage("Step 2: Initializing offscreen headless EGL...")
            engine.init()
            logMessage("Step 3: Creating ROBUST EGL context (0x30BF=1, 0x31BD=0x31BE)...")
            engine.createContext(enableRobustness = true)
            engine.makeCurrent()

            logMessage("Step 4: Compiling & linking Safe Shader (Loop Unrolled with Static Constants) under Robust context...")
            val res = ShaderTestSuite.testShader(
                variantName = "Shader Variant C (Safe Workaround)",
                description = "Loop unrolled with static constants (Safe under robust access)",
                vertexSource = "// Salt: safe_${System.nanoTime()}\n${ShaderTestSuite.VERTEX_SHADER_C}",
            )
            logMessage(res.formattedOutput())

            if (res.linkSuccess) {
                logMessage("RESULT: ROBUST SAFE TEST PASSED (Link Status: 1).")
                logMessage("  Proves: Robust EGL contexts link cleanly when dynamic uniform indexing is not used.")
            } else {
                logMessage("RESULT: FAILED unexpectedly: ${res.linkInfoLog}")
            }
        } finally {
            engine.destroy()
        }
    }

    /**
     * Button 3: Direct Driver Bug (Robust + Dynamic Indexing) [Expect: FAIL]
     * Creates an EGL context with EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT = 0x30BF.
     * Compiles Dynamic Indexing Shader (dynamic uniform array indexing).
     * Proves: The direct root cause: Qualcomm Adreno's bounds-checking pass (GVI) aborts on dynamic uniform indexing.
     */
    private fun executeTriggerGviCrashTest() {
        isProcessPoisonedByRobustContext = true
        logMessage("Step 1: Clearing shader disk cache to force fresh driver compilation...")
        ShaderCacheUtil.disableShaderDiskCache(this)

        val engine = EglEngine()
        try {
            logMessage("Step 2: Initializing offscreen headless EGL...")
            engine.init()
            logMessage("Step 3: Creating ROBUST EGL context (0x30BF=1, 0x31BD=0x31BE)...")
            engine.createContext(enableRobustness = true)
            engine.makeCurrent()

            logMessage("Step 4: Compiling & linking Dynamic Indexing Shader under Robust Context...")
            logMessage("Expected on Qualcomm Adreno 6xx/7xx: Fails with:")
            logMessage("  Assertion failed: GVI && \"cannot compute gv size for oob (no global info)\"")

            val result = ShaderTestSuite.testDynamicIndexingShader(salt = "direct_crash_${System.nanoTime()}")
            logMessage(result.formattedOutput())

            if (!result.linkSuccess) {
                logMessage("[DRIVER BUG CONFIRMED!] Dynamic Indexing Shader failed with expected assertion:")
                logMessage("  ${result.linkInfoLog}")
            } else {
                logMessage("RESULT: Dynamic Indexing Shader unexpectedly linked successfully. Driver may have patched this specific shader.")
            }
        } finally {
            engine.destroy()
        }
    }

    /**
     * Button 4: Cross-Context Poisoning Test [Expect: BLEED / FAIL]
     * Demonstrates cross-context state bleeding between two independent contexts:
     *
     * 1. Thread B (Context B1 - Standard Context Pre-Check):
     *    Verifies that Dynamic Indexing Shader compiles cleanly on a Standard Context BEFORE robust context exists.
     *
     * 2. Thread A (Context A - Robust Context):
     *    Creates a ROBUST EGL context (0x30BF=1).
     *    Links the SAFE shader from Button 2. Result: SUCCESS (100% clean).
     *
     * 3. Thread B (Context B2 - Standard Context Post-Check):
     *    Creates a STANDARD EGL context with ZERO robust attributes: attribs=[0x3098, 2, 0x3038].
     *    Links Dynamic Indexing Shader (the EXACT shader that passed in Step 1!).
     *
     * 4. Result:
     *    Thread B FAILS with the GVI assertion on the standard context!
     *    Proves: Context A's robust access permanently leaked into Context B across the process.
     */
    private fun executePoisoningTest() {
        logMessage("Clearing shader disk cache before cross-context poisoning test...")
        ShaderCacheUtil.disableShaderDiskCache(this)

        logMessage("==================================================")
        logMessage(">>> STEP 1: Thread B pre-check on STANDARD context (ZERO robust attributes)...")
        logMessage("  Thread B attribs: [0x3098=2, 0x3038=EGL_NONE]")

        val standardPreEngine = EglEngine()
        var preCheckPassed = false
        try {
            standardPreEngine.init()
            standardPreEngine.createContext(enableRobustness = false)
            standardPreEngine.makeCurrent()
            logMessage("[Thread B] Standard context created and made current.")

            val preSalt = "pre_poison_${System.nanoTime()}"
            val preRes = ShaderTestSuite.testDynamicIndexingShader(salt = preSalt)
            logMessage(preRes.formattedOutput())
            preCheckPassed = preRes.linkSuccess

            if (preCheckPassed) {
                logMessage("[Thread B Pre-Check]: PASSED on standard context as expected.")
            } else {
                logMessage("[Thread B Pre-Check]: FAILED (Process was already poisoned by an earlier robust test in this session).")
            }
        } finally {
            standardPreEngine.destroy(terminateDisplay = false)
        }

        logMessage("--------------------------------------------------")
        logMessage(">>> STEP 2: Thread A creates ROBUST context (0x30BF=1)...")

        isProcessPoisonedByRobustContext = true
        val robustThread = Executors.newSingleThreadExecutor()
        val robustEngine = EglEngine()
        var robustError: Throwable? = null

        robustThread.submit {
            try {
                robustEngine.init()
                robustEngine.createContext(enableRobustness = true)
                robustEngine.makeCurrent()
                logMessage("[Thread A] Robust context created and made current.")

                // Compile safe shader (same as Button 2)
                val prime = ShaderTestSuite.testShader(
                    variantName = "Context A Safe Shader",
                    description = "Shader running inside robust context",
                    vertexSource = "// Salt: ctx_a_${System.nanoTime()}\n${ShaderTestSuite.VERTEX_SHADER_C}",
                )
                logMessage("[Thread A] Safe shader link: ${if (prime.linkSuccess) "SUCCESS" else "FAILED"}")
            } catch (t: Throwable) {
                robustError = t
            }
        }.get()

        if (robustError != null) {
            logMessage("[Thread A ERROR]: ${robustError.message}")
            robustEngine.destroy(terminateDisplay = true)
            robustThread.shutdown()
            return
        }

        logMessage("--------------------------------------------------")
        logMessage(">>> STEP 3: Thread B creates STANDARD context while Thread A robust context is active...")
        logMessage("  Thread B attribs: [0x3098=2, 0x3038=EGL_NONE] (ZERO robust attributes!)")

        val standardPostEngine = EglEngine()
        try {
            standardPostEngine.init()
            standardPostEngine.createContext(enableRobustness = false)
            standardPostEngine.makeCurrent()
            logMessage("[Thread B] Standard context created and made current.")

            logMessage(">>> Thread B links Dynamic Indexing Shader (which passed in Step 1)...")
            val postSalt = "post_poison_${System.nanoTime()}"
            val postRes = ShaderTestSuite.testDynamicIndexingShader(salt = postSalt)
            logMessage(postRes.formattedOutput())

            if (!postRes.linkSuccess) {
                logMessage("[CRITICAL: CROSS-CONTEXT DRIVER BLEEDING CONFIRMED!]")
                logMessage("Context B (STANDARD) FAILED to link Dynamic Indexing Shader!")
                logMessage("  Context B Attribs: [0x3098, 2, 0x3038] (NO ROBUST ACCESS)")
                logMessage("  Assertion Error  : ${postRes.linkInfoLog}")
                logMessage("  Explanation: Robust access from Thread A permanently poisoned the process-wide Qualcomm compiler backend (/vendor/lib64/egl/libGLESv2_adreno.so / libllvm-glnext.so)!")
            } else {
                logMessage("[NO POISONING DETECTED]: Dynamic Indexing Shader linked successfully on standard context.")
            }
        } finally {
            standardPostEngine.destroy(terminateDisplay = false)
            robustThread.submit { robustEngine.destroy(terminateDisplay = true) }.get()
            robustThread.shutdown()
            logMessage("EGL teardown complete.")
        }
    }

    /**
     * Clear Shader Cache:
     * Manually triggers deletion of shader cache files and touches .nocache
     */
    private fun executeClearCache() {
        logMessage("Manually clearing and disabling OpenGL shader disk cache...")
        val messages = ShaderCacheUtil.disableShaderDiskCache(this)
        for (msg in messages) {
            logMessage("  $msg")
        }
        logMessage("Shader disk cache cleared and .nocache files recreated.")
    }
}
